/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ElltyRouteImport } from './routes/ellty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElltyIndexRouteImport } from './routes/ellty/index'
import { Route as ElltyQuickFormStylingRouteImport } from './routes/ellty/quick-form-styling'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ElltyRoute = ElltyRouteImport.update({
  id: '/ellty',
  path: '/ellty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElltyIndexRoute = ElltyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElltyRoute,
} as any)
const ElltyQuickFormStylingRoute = ElltyQuickFormStylingRouteImport.update({
  id: '/quick-form-styling',
  path: '/quick-form-styling',
  getParentRoute: () => ElltyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ellty': typeof ElltyRouteWithChildren
  '/health': typeof HealthRoute
  '/ellty/quick-form-styling': typeof ElltyQuickFormStylingRoute
  '/ellty/': typeof ElltyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/ellty/quick-form-styling': typeof ElltyQuickFormStylingRoute
  '/ellty': typeof ElltyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ellty': typeof ElltyRouteWithChildren
  '/health': typeof HealthRoute
  '/ellty/quick-form-styling': typeof ElltyQuickFormStylingRoute
  '/ellty/': typeof ElltyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ellty'
    | '/health'
    | '/ellty/quick-form-styling'
    | '/ellty/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/ellty/quick-form-styling' | '/ellty'
  id:
    | '__root__'
    | '/'
    | '/ellty'
    | '/health'
    | '/ellty/quick-form-styling'
    | '/ellty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElltyRoute: typeof ElltyRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ellty': {
      id: '/ellty'
      path: '/ellty'
      fullPath: '/ellty'
      preLoaderRoute: typeof ElltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ellty/': {
      id: '/ellty/'
      path: '/'
      fullPath: '/ellty/'
      preLoaderRoute: typeof ElltyIndexRouteImport
      parentRoute: typeof ElltyRoute
    }
    '/ellty/quick-form-styling': {
      id: '/ellty/quick-form-styling'
      path: '/quick-form-styling'
      fullPath: '/ellty/quick-form-styling'
      preLoaderRoute: typeof ElltyQuickFormStylingRouteImport
      parentRoute: typeof ElltyRoute
    }
  }
}

interface ElltyRouteChildren {
  ElltyQuickFormStylingRoute: typeof ElltyQuickFormStylingRoute
  ElltyIndexRoute: typeof ElltyIndexRoute
}

const ElltyRouteChildren: ElltyRouteChildren = {
  ElltyQuickFormStylingRoute: ElltyQuickFormStylingRoute,
  ElltyIndexRoute: ElltyIndexRoute,
}

const ElltyRouteWithChildren = ElltyRoute._addFileChildren(ElltyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElltyRoute: ElltyRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
